-- Sprint Hotfix: customer code auto numbering
-- Ensures every customer has a unique 4-digit code generated by the system.

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('customers.code.autonumber'));

DO $$
DECLARE
    customer_record RECORD;
    next_number INTEGER;
    next_code TEXT;
BEGIN
    SELECT COALESCE(MAX(code::integer), 0) + 1
      INTO next_number
      FROM customers
     WHERE code ~ '^[0-9]+$';

    FOR customer_record IN
        SELECT id
          FROM customers
         WHERE code IS NULL OR btrim(code) = ''
         ORDER BY id
         FOR UPDATE
    LOOP
        LOOP
            next_code := lpad(next_number::text, 4, '0');
            EXIT WHEN NOT EXISTS (SELECT 1 FROM customers WHERE code = next_code);
            next_number := next_number + 1;
        END LOOP;

        UPDATE customers
           SET code = next_code,
               updated_at = NOW()
         WHERE id = customer_record.id;

        next_number := next_number + 1;
    END LOOP;
END $$;

COMMIT;
